POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMWM0ZTBlMzEwZWQxM2NhNDUyY2MxMyIsImlhdCI6MTU5NTcxMzI1MX0.mxBHbHy2kejdV8lTuOEYrGRUl23zJ9lYzh7KUf9vaVI

{
    "title": "A new blog post by root",
    "author": "root",
    "url": "https://www.google.com",
    "likes": 7,
    "userId": "5f1c4e0e310ed13ca452cc13"
}