POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Here is another blog post",
    "author": "Test author 3",
    "url": "https://www.google.com",
    "likes": 7,
    "userId": "5f1c4e52310ed13ca452cc14"
}